### ISSUE TITLE
Version 1.1.3 won't start within 1.19.3

### ISSUE THREAD

**Issue by Cape-City** [d4rkm0nkey/minecraft-talking-villagers#2]
Hi,

the Mod wants a MC Version 1.18.x installed, but i can't download any other Version from this Mod on CurseForge:

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Talking Villagers' (talking-villagers) 1.1.3 with any version that is compatible with:
		 - minecraft 1.19.3
Unmet dependency listing:
	 - Mod 'Statement Vanilla Compatibility Module' (statement_vanilla_compatibility) 1.0.1+1.14.4-1.15.2 requires any version between 1.14.0-0 (inclusive) and 1.16.0-0 (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.3!
	 - Mod 'Talking Villagers' (talking-villagers) 1.1.3 requires any 1.18.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.3!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Cape-City** [comment]
Found the bug, created a pull request.
